### ISSUE TITLE
Bad sad error  in windows

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/module-ballerinax-aws.s3#36] opened 2021-01-31 09:59 UTC
**Description:**
In windows environments following code gives a bad sad error.

```ballerina
import ballerinax/aws.s3;
import ballerina/config;
import ballerina/http;
import ballerina/io;

 // Create the ClientConfiguration that can be used to connect with the Amazon S3 service..
s3:ClientConfiguration amazonS3Config = {
    accessKeyId: config:getAsString("ACCESS_KEY_ID"),
    secretAccessKey: config:getAsString("SECRET_ACCESS_KEY"),
    region: config:getAsString("REGION"),
    clientConfig: {
        http1Settings: {chunking: http:CHUNKING_NEVER},
        secureSocket:{
            trustStore:{
                path: config:getAsString("TRUST_STORE_PATH"),
                password: config:getAsString("TRUST_STORE_PASSWORD")
            }
        }
    }
};

s3:AmazonS3Client|s3:ConnectorError amazonS3Client = new(amazonS3Config);

public function main() {
    // Create the AmazonS3 client with amazonS3Config. 
    s3:AmazonS3Client|s3:ConnectorError amazonS3Client = new(amazonS3Config);
    if (amazonS3Client is s3:AmazonS3Client) {
        string bucketName = "sample-amazon-bucket";
        s3:CannedACL cannedACL = s3:ACL_PRIVATE;
        // Invoke createBucket remote function using base/parent Amazon S3 client.
        s3:ConnectorError? createBucketResponse = amazonS3Client->createBucket(bucketName, cannedACL);
        if (createBucketResponse is s3:ConnectorError) {
            // If unsuccessful, print the error returned.
            io:println("Error: ");
        } else {
            // If successful, print the status of the operation.
            io:println("Bucket Creation Status: Success");
        }
    } else {
        io:print("errro");
    }
}
```

Error: in ballerina-internal.log

```
[2021-01-23 14:03:02,080] SEVERE {b7a.log.crash} - Illegal char <:> at index 6: src\/D:/src/aws.s3/amazonS3_sort.bal\/D:/src/aws.s3/amazonS3_sort.bal
java.nio.file.InvalidPathException: Illegal char <:> at index 6: src\/D:/src/aws.s3/amazonS3_sort.bal\/D:/src/aws.s3/amazonS3_sort.bal
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.getCUnitASTHolder(DefaultObservabilitySymbolCollector.java:174)
        at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.getModuleASTHolder(DefaultObservabilitySymbolCollector.java:152)
        at org.ballerinalang.observability.anaylze.DefaultObservabilitySymbolCollector.process(DefaultObservabilitySymbolCollector.java:87)
        at org.wso2.ballerinalang.compiler.CompilerDriver.generateObservabilityData(CompilerDriver.java:331)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:308)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:260)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:257)
        at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:143)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:176)
        at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:221)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:101)
        at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:109)
```
```

**Version:**
Ballerina SLP5

**Comment by Chuhaa** [comment] 2021-03-24 13:17
Fixed by SLAlpha2 migration. We could not reproduce this issue in SLAlpha2 version connector.
Sample code - https://github.com/ballerina-platform/module-ballerinax-aws.s3/blob/master/samples/create_bucket.bal

**Comment by abeykoon** [comment] 2021-09-24 09:40
Closing as resolved.

**Closed by abeykoon** 2021-09-24 09:40 UTC
Labels: Type/Bug
